<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ef4444;
        }
        .header h1 {
            color: #dc2626;
            margin: 0;
            font-size: 20px;
        }
        .meta {
            margin-bottom: 20px;
        }
        .meta table {
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #fef2f2;
            color: #991b1b;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #fee2e2;
            text-transform: uppercase;
            font-size: 9px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }
        .text-end {
            text-align: right;
        }
        .status-paid { color: #10b981; }
        .status-pending { color: #f59e0b; }
        .status-overdue { color: #ef4444; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated On: {{ date('d-m-Y H:i') }}</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Report Type:</strong> Expense Analysis</td>
                <td class="text-end"><strong>Generated By:</strong> Finance Manager</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Company</th>
                <th>Expense Name</th>
                <th>Category</th>
                <th class="text-end">Planned Amount</th>
                <th class="text-end">Actual Paid</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php 
                $totalPlanned = 0;
                $totalActual = 0;
            @endphp
            @foreach($expenses as $expense)
                @php
                    $planned = $expense->planned_amount ?? 0;
                    $actual = $expense->actual_amount ?? 0;
                    
                    $totalPlanned += $planned;
                    $totalActual += $actual;
                @endphp
                <tr>
                    <td>{{ $expense->payment_date ?? $expense->created_at->format('d-m-Y') }}</td>
                    <td>{{ $expense->company->name ?? 'N/A' }}</td>
                    <td>{{ $expense->expense_name }}</td>
                    <td>{{ $expense->categoryRelation->name ?? 'Uncategorized' }}</td>
                    <td class="text-end">₹ {{ number_format($planned, 2) }}</td>
                    <td class="text-end">₹ {{ number_format($actual, 2) }}</td>
                    <td>
                        <span class="status-{{ $expense->status }}">
                            {{ ucfirst($expense->status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #fef2f2; font-weight: bold;">
                <td colspan="4">TOTALS</td>
                <td class="text-end">₹ {{ number_format($totalPlanned, 2) }}</td>
                <td class="text-end">₹ {{ number_format($totalActual, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Finance Management System | Consolidated Expense Report
    </div>
</body>
</html>
