<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }} - {{ $period }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #10b981;
        }
        .header h1 {
            color: #059669;
            margin: 0;
            font-size: 20px;
        }
        .meta {
            margin-bottom: 20px;
        }
        .meta table {
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f0fdf4;
            color: #166534;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #dcfce7;
            text-transform: uppercase;
            font-size: 9px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }
        .text-end {
            text-align: right;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Period: {{ date('F Y', strtotime($period . '-01')) }}</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Generated On:</strong> {{ date('d-m-Y H:i') }}</td>
                <td class="text-end"><strong>Tax Type:</strong> GST Report</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Company</th>
                <th>Party Name</th>
                <th>Bill No</th>
                <th class="text-end">Taxable Amount</th>
                <th class="text-end">GST %</th>
                <th class="text-end">GST Amount</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            @php 
                $totalTaxable = 0;
                $totalGst = 0;
            @endphp
            @foreach($taxes as $tax)
                @php
                    $taxable = $tax->taxable;
                    $partyName = '-';
                    if ($tax->taxable_type === 'App\Models\Income') {
                        $partyName = $taxable->party_name ?? $taxable->client_name ?? '-';
                    } elseif ($tax->taxable_type === 'App\Models\Expense') {
                        $partyName = $taxable->vendor_name ?? $taxable->party_name ?? '-';
                    }
                    
                    $amount = $taxable->amount ?? 0;
                    $totalTaxable += $amount;
                    $totalGst += $tax->tax_amount;
                @endphp
                <tr>
                    <td>{{ $tax->created_at->format('d-m-Y') }}</td>
                    <td>{{ $taxable->company->name ?? 'N/A' }}</td>
                    <td>{{ $partyName }}</td>
                    <td>{{ $taxable->bill_no ?? $taxable->invoice_number ?? '-' }}</td>
                    <td class="text-end">₹ {{ number_format($amount, 2) }}</td>
                    <td class="text-end">{{ $tax->tax_percentage }}%</td>
                    <td class="text-end">₹ {{ number_format($tax->tax_amount, 2) }}</td>
                    <td>{{ ucfirst($tax->direction) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #f0fdf4; font-weight: bold;">
                <td colspan="4">TOTALS</td>
                <td class="text-end">₹ {{ number_format($totalTaxable, 2) }}</td>
                <td></td>
                <td class="text-end">₹ {{ number_format($totalGst, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Finance Management System | Exported via GST Module
    </div>
</body>
</html>
