<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #3b82f6;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 20px;
        }
        .meta {
            margin-bottom: 20px;
        }
        .meta table {
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #eff6ff;
            color: #1e40af;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #dbeafe;
            text-transform: uppercase;
            font-size: 9px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }
        .text-end {
            text-align: right;
        }
        .status-received { color: #10b981; }
        .status-pending { color: #f59e0b; }
        .status-overdue { color: #ef4444; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Period: {{ ucfirst($period) }}</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Generated On:</strong> {{ date('d-m-Y H:i') }}</td>
                <td class="text-end"><strong>Report Type:</strong> Financial Statement</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Company</th>
                <th>Party Name</th>
                <th class="text-end">Planned Amount</th>
                <th class="text-end">Received Amount</th>
                <th class="text-end">Balance</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php 
                $totalPlanned = 0;
                $totalReceived = 0;
                $totalBalance = 0;
            @endphp
            @foreach($incomes as $income)
                @php
                    $planned = $income->amount ?? 0;
                    $received = $income->actual_amount ?? $income->received_amount ?? 0;
                    $balance = $planned - $received;
                    
                    $totalPlanned += $planned;
                    $totalReceived += $received;
                    $totalBalance += $balance;
                @endphp
                <tr>
                    <td>{{ $income->income_date ?? $income->created_at->format('d-m-Y') }}</td>
                    <td>{{ $income->company->name ?? 'N/A' }}</td>
                    <td>{{ $income->party_name ?? '-' }}</td>
                    <td class="text-end">₹ {{ number_format($planned, 2) }}</td>
                    <td class="text-end">₹ {{ number_format($received, 2) }}</td>
                    <td class="text-end">₹ {{ number_format($balance, 2) }}</td>
                    <td>
                        <span class="status-{{ $income->status }}">
                            {{ ucfirst($income->status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #eff6ff; font-weight: bold;">
                <td colspan="3">TOTALS</td>
                <td class="text-end">₹ {{ number_format($totalPlanned, 2) }}</td>
                <td class="text-end">₹ {{ number_format($totalReceived, 2) }}</td>
                <td class="text-end">₹ {{ number_format($totalBalance, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Finance Management System | Confidential Financial Data
    </div>
</body>
</html>
