<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TDS {{ $type }} Report - {{ $period }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #6366f1;
        }
        .header h1 {
            color: #4f46e5;
            margin: 0;
            font-size: 20px;
        }
        .meta {
            margin-bottom: 20px;
        }
        .meta table {
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f8fafc;
            color: #64748b;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #e2e8f0;
            text-transform: uppercase;
            font-size: 9px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }
        .text-end {
            text-align: right;
        }
        .total-box {
            background-color: #f8fafc;
            padding: 10px;
            border-radius: 5px;
            margin-top: 20px;
        }
        .status-paid { color: #10b981; }
        .status-pending { color: #f59e0b; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>TDS {{ $type }} Report</h1>
        <p>Period: {{ date('F Y', strtotime($period . '-01')) }}</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Generated On:</strong> {{ date('d-m-Y H:i') }}</td>
                <td class="text-end"><strong>Company:</strong> All Managed Companies</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Company</th>
                <th>Party Name</th>
                <th class="text-end">Taxable Amount</th>
                <th class="text-end">TDS %</th>
                <th class="text-end">TDS Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php 
                $totalTaxable = 0;
                $totalTds = 0;
            @endphp
            @foreach($taxes as $tax)
                @php
                    $taxable = $tax->taxable;
                    $partyName = '-';
                    if ($tax->taxable_type === 'App\Models\Income') {
                        $partyName = $taxable->party_name ?? $taxable->client_name ?? '-';
                    } elseif ($tax->taxable_type === 'App\Models\Expense') {
                        $partyName = $taxable->vendor_name ?? $taxable->party_name ?? '-';
                    }
                    
                    $amount = $taxable->amount ?? 0;
                    $totalTaxable += $amount;
                    $totalTds += $tax->tax_amount;
                @endphp
                <tr>
                    <td>{{ $tax->created_at->format('d-m-Y') }}</td>
                    <td>{{ $taxable->company->name ?? 'N/A' }}</td>
                    <td>{{ $partyName }}</td>
                    <td class="text-end">₹ {{ number_format($amount, 2) }}</td>
                    <td class="text-end">{{ $tax->tax_percentage }}%</td>
                    <td class="text-end">₹ {{ number_format($tax->tax_amount, 2) }}</td>
                    <td>
                        <span class="status-{{ $tax->payment_status }}">
                            {{ ucfirst($tax->payment_status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #f8fafc; font-weight: bold;">
                <td colspan="3">TOTALS</td>
                <td class="text-end">₹ {{ number_format($totalTaxable, 2) }}</td>
                <td></td>
                <td class="text-end">₹ {{ number_format($totalTds, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Finance Management System | Page 1
    </div>
</body>
</html>
